server.port=8081

logging.level.root=INFO
logging.level.com.app.employee_management=DEBUG
logging.level.org.springframework.web=DEBUG

#/actuator/info
management.endpoints.web.exposure.include=health,info,metrics,loggers,env
management.endpoint.health.show-details=always
management.endpoint.info.enabled=true

management.info.env.enabled=true

info.app.name=Employee Management & Workflow System
info.app.version=1.0.0
info.app.owner=B
app.notification = email

